### PR TITLE
Add databricks/dolly

### PR DESCRIPTION
**Pull request by nicognaW**
Though it's not a ready-to-use model or chat system, it's pretty good training resource for fine-tuning.

### CODE REVIEW

**Comment by nichtdax** [comment]
Could you please append this to the end of the readme file?

**Comment by nichtdax** [comment]
LGTM

**Comment by matthayes** [comment]
Hi, we have released the Dolly model on Hugging Face: https://huggingface.co/databricks/dolly-v1-6b

**Comment by nicognaW** [comment]
> Hi, we have released the Dolly model on Hugging Face: https://huggingface.co/databricks/dolly-v1-6b

Thanks for the message, I will add it to the list.

**Pull request merged**
