### PR TITLE
Add more LLaMA based projects & better organize LLaMA-derived projects

### PR DESCRIPTION
**Pull request by nicognaW**

### CODE REVIEW

**Comment by nichtdax** [comment]
[hpcaitech/ColossalAI](https://github.com/hpcaitech/ColossalAI) is a framework to parallel train the large models. They cover lots of models. It's not based on LLaMA directly tho. Please remove it

**Comment by alreadydone** [comment]
But their "chat" version, ColossalChat, is indeed based on LLaMA, see [blog post](https://medium.com/@yangyou_berkeley/colossalchat-an-open-source-solution-for-cloning-chatgpt-with-a-complete-rlhf-pipeline-5edf08fb538b). I suggest that you link to the blog post instead to avoid confusion.

**Comment by alreadydone** [comment]
Please also add [lm-sys/FastChat](https://github.com/lm-sys/FastChat) "Vicuna"

**Comment by nichtdax** [comment]
> But their "chat" version, ColossalChat, is indeed based on LLaMA, see [blog post](https://medium.com/@yangyou_berkeley/colossalchat-an-open-source-solution-for-cloning-chatgpt-with-a-complete-rlhf-pipeline-5edf08fb538b). I suggest that you link to the blog post instead to avoid confusion.

I agree with you, [the blog link](https://scribe.rip/@yangyou_berkeley/colossalchat-an-open-source-solution-for-cloning-chatgpt-with-a-complete-rlhf-pipeline-5edf08fb538b) should be added

**Comment by nicognaW** [comment]
Note that I removed antimatter15/alpaca.cpp because the original ggerganov/llama.cpp now supports alpaca, and it's far behind the origin.

**Comment by nichtdax** [comment]
LGTM

**Pull request merged**
