### PR TITLE
added chatglm

### PR DESCRIPTION
**Pull request by jasonborn0**

### CODE REVIEW

**Comment by nichtdax** [comment]
LGTM

**Comment by nichtdax** [comment]
Next time, append the new project at the end of the file, please

**Comment by jasonborn0** [comment]
Noted, but why don't we sort by alphabet?

**Comment by nichtdax** [comment]
I haven't thought of that. Tags are just for brief description of the project. On the second thought, it could be good for people finding project tags-wise. But I still think chronological order is easy to maintain. Plus people have Ctrl F anyway.

**Pull request merged**
